### ISSUE TITLE
Enderchest GUI's Title error

### ISSUE THREAD

**Issue by CrystallRPG** [minion325/BetterEnderChests#7]
Minecraft 1.19.4 last Paper release build 538

Opening the enderchest (via command or placed enderchest) the GUI's tittle are "`VECEnderchest:X:PlayerName`" where X is a number from 1 to 6, and PlayerName is the actual player name instead of the `enderchest-names:` data in `.yml`

![image](https://github.com/minion325/VariableEnderChests/assets/126920403/9019f11a-d532-48dc-abbf-8c9147dea868)

**Comment by minion325** [comment]
What version of VariableEnderChests are you using?
Also can you send your server startup log?

**Comment by minion325** [comment]
You can also join my discord for faster communication

**Comment by CrystallRPG** [comment]
> You can also join my discord for faster communication

where can i get the link?

**Comment by minion325** [comment]
> > You can also join my discord for faster communication
> 
> where can i get the link?

https://discord.gg/69qtbPpnHN

**Comment by CrystallRPG** [comment]
> Opening the enderchest (via command or placed enderchest) the GUI's tittle are "`VECEnderchest:X:PlayerName`" where X is a number from 1 to 6, and PlayerName is the actual player name instead of the `enderchest-names:` data in `.yml`

https://discord.com/channels/974082563159244851/978498767286313020/1111043209305542666
