### ISSUE TITLE
Suggestion: Add option in config to disable saving data

### ISSUE THREAD

**Issue by NoltoxGit** [minion325/BetterEnderChests#8]
Hello !

Can you add an option in config.yml to disable the message when a player connects please?
- `[VariableEnderChests] Loaded enderchest for ...`
- `[VariableEnderChests] Saving data for ...`

Thank you so much :)

**Comment by minion325** [comment]
Sure I'll see to add it in a future update. Note however, if a bug does arise within the plugin, those messages are useful for me to debug with. If you have them disabled and submit a bug report it becomes much harder to find the soirce of the bug.
